SPOOL solution11 
SET ECHO ON  
SET FEEDBACK ON 
SET LINESIZE 100 
SET PAGESIZE 200 

ALTER TABLE SUPPLIER ADD TOTAL_SUPPLIED_PARTS NUMBER(6)
    CONSTRAINT SUPPLIER_CHECK2 CHECK(TOTAL_SUPPLIED_PARTS >= 0);

UPDATE SUPPLIER tt
SET    (TOTAL_SUPPLIED_PARTS) = (SELECT COUNT(*)
                                FROM PARTSUPP st
                                WHERE  st.PS_SUPPKEY = tt.S_SUPPKEY)                         
WHERE  EXISTS (SELECT 1
               FROM   PARTSUPP
               WHERE  PS_SUPPKEY = tt.S_SUPPKEY);

SPOOL OFF