SELECT (SELECT COUNT(*) FROM ALLDRINKS ) "ALLDRINKS",
       (SELECT COUNT(*) FROM DRINKERS ) "DRINKERS",
       (SELECT COUNT(*) FROM LOCATED ) "LOCATED",
       (SELECT COUNT(*) FROM SERVES ) "SERVES",
       (SELECT COUNT(*) FROM LIKES ) "LIKES",
       (SELECT COUNT(*) FROM ORDERS ) "ORDERS"
FROM DUAL;

