CREATE TABLE ALLDRINKS(	 /* All legal drinks */
DRINK		VARCHAR(30)	NOT NULL,	/* Drink name	*/
	CONSTRAINT DRINKNAME_PKEY PRIMARY KEY(DRINK) );

CREATE TABLE DRINKERS ( /* All drinkers */
DRINKER	VARCHAR(30)	NOT NULL,
	CONSTRAINT DRINKERS_PKEY PRIMARY KEY (DRINKER));

CREATE TABLE LOCATED(	/* Pubs have locations */
PUB			VARCHAR(30)	NOT NULL,	/* Pub name	*/
STREET		VARCHAR(30)	NOT NULL,	/* Street name	*/
BLDG_NO		DECIMAL(4)	NOT NULL,	/* Building number	*/
	CONSTRAINT LOCATED_PKEY PRIMARY KEY(PUB) );

CREATE TABLE SERVES(	/* Pubs serve drinks */
PUB			VARCHAR(30)	NOT NULL,	/* Pub name	*/
DRINK		VARCHAR(30)	NOT NULL,	/* Drink name	*/
PRICE		DECIMAL(5,2)	NOT NULL,	/* Drink price	*/
	CONSTRAINT SERVES_PKEY PRIMARY KEY(PUB, DRINK),
        CONSTRAINT SERVES_FKEY1 FOREIGN KEY(PUB) 
		REFERENCES LOCATED(PUB),
	CONSTRAINT SERVES_FKEY2 FOREIGN KEY(DRINK)
		REFERENCES ALLDRINKS(DRINK)  );

CREATE TABLE LIKES(	/* Drinkers like drinks	*/
DRINKER		VARCHAR(30)	NOT NULL,	/* Drinker name	*/
DRINK		VARCHAR(30)	NOT NULL,	/* Drink name	*/
RATING		DECIMAL(1)	NOT NULL,	/* Rating of the drink	*/
	CONSTRAINT LIKES_PKEY PRIMARY KEY(DRINKER, DRINK),
   	CONSTRAINT LIKES_FKEY1 FOREIGN KEY(DRINK) REFERENCES ALLDRINKS(DRINK),
	CONSTRAINT LIKES_DKEY2 FOREIGN KEY(DRINKER) REFERENCES DRINKERS(DRINKER));

CREATE TABLE ORDERS(	/* Drinkers visit pubs and consumes drinks */
DRINKER		VARCHAR(30)	NOT NULL,	/* Drinker name	*/
PUB			VARCHAR(30)	NOT NULL,	/* Pub name	*/
ODATE		DATE		NOT NULL,	/* Order date	*/
DRINK		VARCHAR(30)	NOT NULL,	/* Drink name	*/
DRINK_NO	DECIMAL(2)	NOT NULL, 	/* A sequence number of a drink */
	CONSTRAINT ORDERS_PKEY PRIMARY KEY(DRINKER, PUB, ODATE, DRINK, DRINK_NO),
	CONSTRAINT ORDERS_FKEY1 FOREIGN KEY(PUB, DRINK) REFERENCES SERVES(PUB, DRINK),
	CONSTRAINT ORDERS_FKEY2 FOREIGN KEY(DRINKER) REFERENCES DRINKERS(DRINKER)	);


COMMIT;
