SPOOL solution2
SET ECHO ON 
SET FEEDBACK ON 
SET LINESIZE 100 
SET PAGESIZE 200 
SET SERVEROUTPUT ON 

/*(1) First, the script processes SELECT statement given*/
SELECT CUSTOMER.C_CUSTKEY, COUNT(ORDERS.O_CUSTKEY) CNT
FROM CUSTOMER LEFT OUTER JOIN ORDERS
 ON CUSTOMER.C_CUSTKEY = ORDERS.O_CUSTKEY
GROUP BY CUSTOMER.C_CUSTKEY
HAVING COUNT(ORDERS.O_CUSTKEY) > 20 OR
 COUNT(ORDERS.O_CUSTKEY) = 0
ORDER BY CNT ASC;

/*(2) Next, the script stores PL/SQL function in a data dictionary*/
CREATE OR REPLACE FUNCTION SPECIFIC_CUSTOMERS(customerKey IN NUMBER) RETURN 
VARCHAR IS
    orderCount NUMBER;
BEGIN
    SELECT COUNT(ORDERS.O_CUSTKEY)
    INTO orderCount
    FROM ORDERS
    WHERE ORDERS.O_CUSTKEY=customerKey;     
    RETURN(orderCount);
EXCEPTION
  WHEN NO_DATA_FOUND THEN
   RETURN('');
END SPECIFIC_CUSTOMERS;
/

/*(3) Next, the script processes SELECT statement that uses the stored function to retrieve
the same results as the original statement*/
SELECT * FROM(
SELECT C_CUSTKEY, SPECIFIC_CUSTOMERS(C_CUSTKEY) AS CNT
FROM CUSTOMER)
WHERE CNT=0 OR CNT>=20
ORDER BY CNT ASC;

/*(4) Finally, the script drops the stored function.*/
DROP FUNCTION SPECIFIC_CUSTOMERS;

SPOOL OFF