use csit115;
CREATE TABLE DEPARTMENT(
	name VARCHAR(30) NOT NULL, 
    address VARCHAR(100) NOT NULL, 
    phone VARCHAR(20) NOT NULL, 
    CONSTRAINT DEPT_PK PRIMARY KEY(name) );
    
INSERT INTO DEPARTMENT VALUES ('Sales', '123 Market Street, Wollongong', '024123567');
SELECT * FROM DEPARTMENT;
DROP TABLE DEPARTMENT;